if(CONFIG_HAS_CC13X2_CC26X2_SDK OR CONFIG_HAS_CC13X2X7_CC26X2X7_SDK OR CONFIG_HAS_CC3220SDK OR CONFIG_HAS_MSP432P4XXSDK)
add_subdirectory(simplelink)
endif()
if(CONFIG_HAS_CC23X0_SDK OR CONFIG_HAS_CC27XXX10_SDK OR CONFIG_HAS_CC27XXX20_SDK)
add_subdirectory(simplelink_lpf3)
endif()
if(CONFIG_HAS_CC35XX_SDK)
add_subdirectory(simplelink_wff3)
endif()
