# Copyright (c) 2024-2026, Texas Instruments Incorporated
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# *  Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# *  Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# *  Neither the name of Texas Instruments Incorporated nor the names of
#    its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# All targets in this file are for Cortex-M0P

add_subdirectory(source/ti/devices)
add_subdirectory(source/ti/boards)

include(${CMAKE_CURRENT_LIST_DIR}/CMakeSources.cmake)

add_subdirectory_ifdef(CONFIG_BT source/ti/ble)

if(CONFIG_HAS_CC23X0_SDK)

  if(CONFIG_SOC_CC2340R5)
    zephyr_compile_definitions(DeviceFamily_CC23X0R5 ${COMPILER})
  endif()

  if(CONFIG_SOC_CC2340R53)
    zephyr_compile_definitions(DeviceFamily_CC23X0R5 ${COMPILER})
  endif()

  if(CONFIG_SOC_CC2340R5_WCSP)
      zephyr_compile_definitions(DeviceFamily_CC23X0R5 ${COMPILER})
  endif()

  if(CONFIG_SOC_CC2340R5MODA)
    zephyr_compile_definitions(DeviceFamily_CC23X0R5 ${COMPILER})
  endif()

  zephyr_include_directories(
    .
    source
    )

  zephyr_library()
  zephyr_library_compile_definitions(${COMPILER})
  zephyr_library_sources(
    ${SOURCES_DRIVERS_LPF3}
    ${SOURCES_DRIVERS_CC23X0}
    ${SOURCES_KERNEL}
    ${SOURCES_OVERLOADS}
    )
  zephyr_link_libraries(
    ${CMAKE_CURRENT_SOURCE_DIR}/source/third_party/ecc/lib/gcc/m0p/ecc.a
    )
  zephyr_linker_sources(RAM_SECTIONS
    ${CMAKE_CURRENT_SOURCE_DIR}/source/ti/drivers/dma/dma.ld
  )

  # Radio Control Layer (RCL) driver
  if(CONFIG_SIMPLELINK_F3_RADIO_DRIVER)
    zephyr_library_sources(
        ${SOURCES_RCL}
        ${SOURCES_RCL_LPF3}
      )
  endif()

endif()

if(CONFIG_HAS_CC27XX_SDK)

  if(CONFIG_SOC_CC2745R10_Q1)
    zephyr_compile_definitions(DeviceFamily_CC27XX ${COMPILER})
  endif()

  if(CONFIG_SOC_CC2755R10)
    zephyr_compile_definitions(DeviceFamily_CC27XX ${COMPILER})
  endif()

  if(CONFIG_SOC_CC2755P10)
    zephyr_compile_definitions(DeviceFamily_CC27XX ${COMPILER})
  endif()

  zephyr_include_directories(
    .
    source
    )

  zephyr_library()
  zephyr_library_compile_definitions(${COMPILER})
  zephyr_library_sources(
    ${SOURCES_DRIVERS_LPF3}
    ${SOURCES_DRIVERS_CC27XX}
    ${SOURCES_KERNEL}
    ${SOURCES_OVERLOADS}
    )
  zephyr_link_libraries(
    ${CMAKE_CURRENT_SOURCE_DIR}/source/third_party/ecc/lib/gcc/m33f/ecc.a
    )
  zephyr_linker_sources(RAM_SECTIONS
    ${CMAKE_CURRENT_SOURCE_DIR}/source/ti/drivers/dma/dma.ld
  )

  # Radio Control Layer (RCL) driver
  if(CONFIG_SIMPLELINK_F3_RADIO_DRIVER)
    zephyr_library_sources(
        ${SOURCES_RCL}
        ${SOURCES_RCL_LPF3}
      )
  endif()

endif()

zephyr_compile_definitions(
  -DCONFIG_ZEPHYR
)
